package Singleton_Factory_Pattern;

/**
 *This is the factory class for generating domino.
 */
public class DominoFactory {
	
	/** 
	 *The static instance of domino factory
	 */
	private static DominoFactory factory = null;
	
	/**
	 *To initialize the factory instance
	 *@return DominoFactory the instance of domino factory
	 */
	public static DominoFactory instance() {
		if(factory == null) factory = new DominoFactory();
		return factory;
	}
	
	/**
	 * To generate the domino using leftvalue and rightvalue
	 * @param leftvalue the left value of domino
	 * @param rightvalue the right value of domino
	 * @return Domino the domino generated by factory instance
	 */
	Domino generateDomino(int leftvalue, int rightvalue){
		return new Domino(leftvalue, rightvalue);
	}
}
